### ISSUE TITLE
Search doesnt work after search API rate limits are reached

### ISSUE THREAD

**Issue by xsh2047** [kavun/spotify-playlist-finder#10]
Recieving this message everytime: "Sorry, I can't search for playlists right now"

**Comment by kavun** [comment]
I plan on adding ads to pay for Google and Bing's search API, but in the meantime they both have a rate limit of queries/day.

Looks like the limit has been reset for today though, happy searching!

**Comment by kavun** [comment]
When the rate limits are reached, you can perform the same search that this app does by searching in Google for

```
site:"spotify.com" inurl:"playlist" "Artist" "Song"
```

**Comment by kavun** [comment]
For next time this happens, I added a more helpful error message in #11

**Comment by xsh2047** [comment]
Oh thanks for the info man. And fast response as well, happy coding. 
Cheers
